apiVersion: apps/v1
kind: Deployment
metadata:
  name: axon-server-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: axon-server
  template:
    metadata:
      labels:
        app: axon-server
    spec:
      containers:
        - name: axon-server
          image: limjun9205/axon:20240222
          ports:
            - containerPort: 8024
            - containerPort: 8124