apiVersion: v1
kind: Service
metadata:
  name: axon-server-service
spec:
  selector:
    app: axon-server
  ports:
    - name: tcp-port-8024
      protocol: TCP
      port: 8024
      targetPort: 8024
    - name: tcp-port-8124
      protocol: TCP
      port: 8124
      targetPort: 8124
  type: LoadBalancer