server:
  port: 8088

spring:
  application:
    name: apigateway-service
  cloud:
    gateway:
      mvc:
        routes:
          - id: coinTrade
            uri: http://localhost:8081/
            predicates:
              - Path=/coinTrade/**
          - id: coinWallet
            uri: http://localhost:8082/
            predicates:
              - Path=/coinWallet/**
          - id: coinHist
            uri: http://localhost:8083/
            predicates:
              - Path=/coinHist/**
          - id: coinMyPage
            uri: http://localhost:8084/
            predicates:
              - Path=/coinMyPage/**
          