apiVersion: apps/v1
kind: Deployment
metadata:
  name: hist
  labels:
    app: hist
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hist
  template:
    metadata:
      labels:
        app: hist
    spec:
      containers:
        - name: hist
          image: limjun9205/hist:2024022201
          ports:
            - containerPort: 8083
          readinessProbe:
            httpGet:
              path: '/coinHist/actuator/health'
              port: 8083
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/coinHist/actuator/health'
              port: 8083
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
