server:
  port: 8082
  
  servlet:
    contextPath: /coinWallet

axon:
  serializer:
    general: xstream
  axonserver:
    servers: localhost:8124
  eventhandling:
    processors:
      name:
        mode: tracking
  
spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
#    hikari:
#      driver-class-name: com.mysql.cj.jdbc.Driver
#      jdbc-url: jdbc:mysql://blog.ctljevhj6vrp.ap-northeast-2.rds.amazonaws.com:3306/blog?serverTimezone=UTC&characterEncoding=UTF-8
#      username: admin
#      password: Wns13579!!
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: myGroup
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      
      #driver-class-name: com.mysql.cj.jdbc.Driver
      #jdbc-url: jdbc:mysql://localhost:3306/blog?serverTimezone=UTC&characterEncoding=UTF-8
      #username: root
      #password: root
      
management:
  endpoints:
    web:
      exposure:
        include: health

cloud:
  aws:
    credentials:
       accessKey: AKIA4HKT3GLZYJVY7U54
       secretKey: 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
    region:
      static: ap-northeast-2
    stack:
      auto: false
    
application:
  bucket:
    name: blog-bucket-920508