apiVersion: apps/v1
kind: Deployment
metadata:
  name: trade
  labels:
    app: trade
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trade
  template:
    metadata:
      labels:
        app: trade
    spec:
      containers:
        - name: trade
          image: limjun9205/trade:2024022201
          ports:
            - containerPort: 8081
          readinessProbe:
            httpGet:
              path: '/coinTrade/actuator/health'
              port: 8081
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/coinTrade/actuator/health'
              port: 8081
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
